### ISSUE TITLE
JavaScript version for integration with, e.g., Grunt or Brunch?

### ISSUE THREAD

**Issue by sathomas** [bdkjones/Kit#1]
Wondering if anyone's started a project to create a JavaScript version of the CodeKit .kit "compiler" that could be integrated into Grunt or Brunch. As much as I like using .kit files, the lack of an OS-agnostic, command-line compiler pretty much rules it out.

**Comment by bdkjones** [comment]
Yes. Someone has built a kit compiler for Node.js. It's on Github somewhere.

-Bryan

**Comment by sathomas** [comment]
Looks like this might be the one:

https://github.com/awebneck/kcomp
