### ISSUE TITLE
Feature request: compression

### ISSUE THREAD

**Issue by ghost** [bdkjones/Kit#10]
Since working with modular structure and source files, it would be nice to get to compress the HTML output to remove the whitespace where appropriate.

**Comment by yratof** [comment]
It would be nice to compress the output (.html files) by removing comments, but straight away I know how much of a nightmare that would be since it reads comments to include everything. Currently using this – https://github.com/gruntjs/grunt-contrib-htmlmin

**Comment by indrekpaas** [comment]
Closing this as the request doesn’t need to be a Kit language feature, but rather a built-in extension or hook in CodeKit using [html-minifier](https://www.npmjs.com/package/html-minifier) or a similar library.
