### ISSUE TITLE
.kit — Code is not being inserted by CodeKit. 

### ISSUE THREAD

**Issue by didacus** [bdkjones/Kit#16]
I am having trouble making kit to work. Right now I am trying to import `test.kit` into the body, however after the build I only have the comment and not the HTML from the import. Do I need to activate any settings in CodeKit to compile this properly?

The files are at the same level, in the root of the folder.

Thank you in advance.

test.kit
```
<div>
  <h1>Hello world</h1>
</div>
```

index.html
```
<body>
  <!-- @import test.kit -->
</body>

```

**Comment by bdkjones** [comment]
Let me guess: the file containing this code ends in *.html, doesn't it?

**Comment by bdkjones** [comment]
Yep. I think you can figure it out from there.

**Comment by didacus** [comment]
Thank you for the quick reply! I was not aware that the hosting file also needs to be `.kit`.

**Comment by bdkjones** [comment]
Why would an HTML file be treated as a Kit file? You can't, for example, write JavaScript in a *.txt file and wonder why it won't load. 

Glad you got it sorted!

**Comment by didacus** [comment]
Just for future reference for the documentation. I understood the `.kit` file purpose. What was not very clear for me from reading the documentation (total noob) was that the ‘host‘ file containing the `@import` also need to be a `.kit`. Thank you once again, I have now implemented the nav from my website using kit. Super handy.
