### ISSUE TITLE
Accept empty var

### ISSUE THREAD

**Issue by emmanuelhonore** [bdkjones/Kit#6]
I would love to see the possibility to declare empty variables, which would be useful in some situation like this one: (you want a prev/nav button but not on the index for ex.)
#### index.kit

```
<!-- $navigation -->
<!--@import header.kit --> 
```
#### somePage.kit

```
<!-- $navigation <nav><a href="nextpage.html">Next Page</a></nav> -->
<!--@import header.kit --> 
```
#### header.kit

```
<h1>My Awesome Site</h1>
<!--$navigation-->
```

**Comment by bdkjones** [comment]
Yep. This is on deck for implementation. There's already an issue for it, so I'm closing this one. Thanks.
